### ISSUE TITLE
希望能够在编译OpenSSH的时候支持多线程编译

### ISSUE THREAD

**Issue by AkarinLiu** [kejilion/sh#15]
我在给我的树莓派更新 OpenSSH，感觉速度慢，查看 htop 发现只占用了一个核心，希望能够给用户一个选择是否使用多线程编译。

**Comment by AkarinLiu** [comment]
![image](https://github.com/kejilion/sh/assets/58081491/d98e1980-3842-4ff5-aae6-e3212a1d8efa)

**Comment by kejilion** [comment]
教我怎么多线程编译？

阿卡林刘 ***@***.***> 于2024年7月6日周六 17:39写道：

**Comment by AkarinLiu** [comment]
#16
