### ISSUE TITLE
甲骨文ubuntu22.04/20.04在最新脚本选择：13-8-debian12进行dd后失联，想救砖但实例无法停止，该怎么办？

### ISSUE THREAD

**Issue by zxlhhyccc** [kejilion/sh#21]
![image](https://github.com/user-attachments/assets/5fdc2ec8-a244-4cef-8414-7dd3b5c244b1)
![image](https://github.com/user-attachments/assets/7761f27e-ca04-481b-b612-0b991405150c)
![image](https://github.com/user-attachments/assets/ce645cc7-0cd4-43af-9b5d-f35fcf7f7821)
![image](https://github.com/user-attachments/assets/e109b369-06b0-4777-b329-f014e5969a78)
![image](https://github.com/user-attachments/assets/1582c707-5474-4613-add4-ea19c04eea93)

**Comment by kejilion** [comment]
有视频救砖教学 刷机有风险 请谨慎操作
