### ISSUE TITLE
Alist 改為 Alist-aria2

### ISSUE THREAD

**Issue by Rayfor000** [kejilion/sh#29]
建議將 Alist 的安裝，改為 https://hub.docker.com/r/xhofe/alist-aria2 這是官方的不過內建 aria2

**Comment by kejilion** [comment]
提供一键安装命令 让我参考下

**Comment by Rayfor000** [comment]
> 提供一键安装命令 让我参考下

直接將 docker_img="xhofe/alist:latest" 改為 docker_img="xhofe/alist-aria2:latest"
其餘都不變

**Comment by kejilion** [comment]
6666
