### ISSUE TITLE
是否可以增加iptables 开启 ICMP Ping 

### ISSUE THREAD

**Issue by sundxfansky** [kejilion/sh#30]
0-13-17 高级防火墙

   1、允许PING设置      

        iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT

        iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT
        
  2、禁止PING设置

        iptables -A INPUT -p icmp --icmp-type 8 -s 0/0 -j DROP

**Comment by kejilion** [comment]
加上啦 去测试下

**Comment by sundxfansky** [comment]
牛，感谢大佬
