### ISSUE TITLE
將 '系统信息查询' 中的單位制度調整

### ISSUE THREAD

**Issue by Rayfor000** [kejilion/sh#32]
![螢幕擷取畫面 2024-10-19 180942](https://github.com/user-attachments/assets/886d65e7-5d62-479b-b767-c46ce92c7454)

**Comment by Rayfor000** [comment]
[ ! -f ~/function.sh ] && bash <(curl -sL raw.ogtt.tk/shell/update-function.sh)
可用於調用函式庫
接著可以直接調用 MEM_USAGE SWAP_USAGE DISK_USAGE INTERFACE -i 完成與左側相同效果

**Comment by Rayfor000** [comment]
$(INTERFACE &>/dev/null && CONVERT_SIZE $rx_bytes) 為進站流量
$(INTERFACE &>/dev/null && CONVERT_SIZE $tx_bytes) 為出站流量

**Comment by kejilion** [comment]
把你的出一套简体中文的吧 直接调用你的 哈哈

**Comment by Rayfor000** [comment]
> 把你的出一套简体中文的吧 直接调用你的 哈哈

![圖片](https://github.com/user-attachments/assets/51988aa8-e690-48e0-8e0e-62ce751f78ea)

**Comment by Rayfor000** [comment]
> 把你的出一套简体中文的吧 直接调用你的 哈哈

SYS_INFO_CN() {
	echo -e "${CLR3}系统信息${CLR0}"
	echo -e "${CLR8}$(LINE = "24")${CLR0}"

	echo -e "- 主机名：\t\t${CLR2}$(hostname)${CLR0}"
	echo -e "- 操作系统：\t\t${CLR2}$(CHECK_OS)${CLR0}"
	echo -e "- 内核版本：\t\t${CLR2}$(uname -r)${CLR0}"
	# echo -e "- 机器ID：\t\t${CLR2}$(UUID)${CLR0}"
	echo -e "- 系统语言：\t\t${CLR2}$LANG${CLR0}"
	echo -e "- Shell版本：\t\t${CLR2}$(SHELL_VER)${CLR0}"
	echo -e "- 上次系统更新：\t${CLR2}$(LAST_UPDATE)${CLR0}"
	echo -e "${CLR8}$(LINE - "32")${CLR0}"

	echo -e "- 架构：\t\t${CLR2}$(uname -m)${CLR0}"
	echo -e "- CPU型号：\t\t${CLR2}$(CPU_MODEL)${CLR0}"
	echo -e "- CPU核心数：\t\t${CLR2}$(nproc)${CLR0}"
	echo -e "- CPU频率：\t\t${CLR2}$(CPU_FREQ)${CLR0}"
	# echo -e "- CPU使用率：\t\t${CLR2}$(CPU_USAGE)${CLR0}"
	# echo -e "- CPU缓存：\t\t${CLR2}$(CPU_CACHE)${CLR0}"
	echo -e "${CLR8}$(LINE - "32")${CLR0}"

	echo -e "- 内存使用：\t\t${CLR2}$(MEM_USAGE)${CLR0}"
	echo -e "- 交换分区使用：\t${CLR2}$(SWAP_USAGE)${CLR0}"
	echo -e "- 磁盘使用：\t\t${CLR2}$(DISK_USAGE)${CLR0}"
	echo -e "- 文件系统类型：\t${CLR2}$(df -T / | awk 'NR==2 {print $2}')${CLR0}"
	echo -e "${CLR8}$(LINE - "32")${CLR0}"

	echo -e "- IPv4地址：\t\t${CLR2}$(IP_ADDR -4)${CLR0}"
	echo -e "- IPv6地址：\t\t${CLR2}$(IP_ADDR -6)${CLR0}"
	echo -e "- MAC地址：\t\t${CLR2}$(MAC_ADDR)${CLR0}"
	echo -e "- 网络提供商：\t\t${CLR2}$(NET_PROVIDER)${CLR0}"
	echo -e "- DNS服务器：\t\t${CLR2}$(DNS_ADDR)${CLR0}"
	# echo -e "- 公网IP：\t\t${CLR2}$(PUBLIC_IP)${CLR0}"
	echo -e "- 网络接口：\t\t${CLR2}$(INTERFACE -i)${CLR0}"
	echo -e "- 系统时区：\t\t${CLR2}$(TIMEZONE -i)${CLR0}"
	# echo -e "- 外部时区：\t\t${CLR2}$(TIMEZONE -e)${CLR0}"
	echo -e "${CLR8}$(LINE - "32")${CLR0}"

	echo -e "- 平均负载：\t\t${CLR2}$(LOAD_AVERAGE)${CLR0}"
	echo -e "- 进程数：\t\t${CLR2}$(ps aux | wc -l)${CLR0}"
	echo -e "- 已安装包数：\t\t${CLR2}$(PKG_COUNT)${CLR0}"
	echo -e "${CLR8}$(LINE - "32")${CLR0}"

	echo -e "- 运行时间：\t\t${CLR2}$(uptime -p | sed 's/up //')${CLR0}"
	echo -e "- 启动时间：\t\t${CLR2}$(who -b | awk '{print $3, $4}')${CLR0}"
	echo -e "${CLR8}$(LINE - "32")${CLR0}"

	echo -e "- 虚拟环境：\t\t${CLR2}$(CHECK_VIRT)${CLR0}"
	echo -e "${CLR8}$(LINE = "24")${CLR0}"
}
於kejilion中增加即可(需於文件首段執行 "[ -f ~/function.sh ] && source ~/function.sh || bash <(curl -sL raw.ogtt.tk/shell/update-function.sh) && source ~/function.sh" )
