### ISSUE TITLE
halo建站失败

### ISSUE THREAD

**Issue by jance-hui** [kejilion/sh#4]
https://github.com/kejilion/sh/blob/0efd9041f366c3f628d578e96339f61e29df2753/kejilion.sh#L1843

使用一键脚本安装的docker并没有设置一个叫做 `web_default` 的network
![image](https://github.com/kejilion/sh/assets/43159982/1e22d6a2-ffa0-4e9d-ae1f-1c6a11dd340b)
 导致halo博客容器无法启动。手工把脚本里面的 `--network web_default` 删除了。

同时脚本里面还发现了有使用 `--network web_default` 的地方 2291行。博主看下到底要不要删掉 `--network web_default` 。

**Comment by kejilion** [comment]
先装环境 就有网络了 再装helo

jance-hui ***@***.***> 于2024年3月22日周五 23:19写道：

**Comment by jance-hui** [comment]
docker是使用一键脚本安装的 6-Docker管理   1-安装更新Docker环境。

**Comment by kejilion** [comment]
10. LDNMP建站    1. 安装LDNMP环境

jance-hui ***@***.***> 于2024年3月23日周六 17:39写道：

**Comment by jance-hui** [comment]
尴尬，没注意到，直接执行的21 仅安装nginx
