### ISSUE TITLE
是不是成肉鸡了

### ISSUE THREAD

**Issue by 84348658** [kejilion/sh#9]
用了你的脚本就这样了，不知道是不是成肉鸡了，后来重装系统不用你的脚本就没出现过。我就用你的脚本装了个宝塔开了个bbr，而且我试了3次都这样，2次警告，我重装，第三次直接停了，哈哈，不敢用了，厉害厉害

![微信图片_20240410211151](https://github.com/kejilion/sh/assets/25034392/871d2448-3113-48ee-813d-3ffcbfc33723)

**Comment by kejilion** [comment]
那就别用了

jied8886 ***@***.***> 于2024年4月10日周三 21:13写道：
